version: '3'
services:
  db:
    image: postgres:latest
    container_name: library_con
#    hostname: myhostname
#    restart: always
    networks:
      - postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=library_system
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local

networks:
  postgres:
    driver: bridge
